services:
  awsconsole:
    build: .
    environment:
      - NODE_ENV=production
      - COOKIE_NAME=user_id
      - COOKIE_MAX_AGE=2592000
    expose:
      - "3000"
    networks:
      - web
    labels:
      caddy: "awsconsole.${HOST_SUFFIX:-localhost}"
      caddy.reverse_proxy: "awsconsole:3000"
